# This GitHub Actions workflow syncs docs and OpenAPI definitions to ReadMe
# Documentation: https://docs.readme.com/main/docs/rdme
name: ReadMe GitHub Action 🦉

on:
  push:
    branches:
      # This workflow will run every time you push code to the following branch
      # Check out GitHub's docs for more info on configuring this:
      # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows
      - master

jobs:
  rdme-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v4
          
      # authentication
      - name: authentication 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/authentication.yaml --key=${{ secrets.README_API_KEY }}

      # project core
      - name: Project core 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/project_core.yaml --key=${{ secrets.README_API_KEY }}

      # project management
      - name: Project management 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/project_management.yaml --key=${{ secrets.README_API_KEY }}

      # ticket operations
      - name: Ticket operations 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/ticket_operations.yaml --key=${{ secrets.README_API_KEY }}

      # project connections
      - name: Project connections 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/project_connections.yaml --key=${{ secrets.README_API_KEY }}

      # project tags & files
      - name: Project tags & files 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/project_tags_files.yaml --key=${{ secrets.README_API_KEY }}

      # project webhooks
      - name: Project webhooks 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/project_webhooks.yaml --key=${{ secrets.README_API_KEY }}

      # project api tokens
      - name: Project API tokens 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/project_api_tokens.yaml --key=${{ secrets.README_API_KEY }}

      # project agent
      - name: Project agent 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/project_agent.yaml --key=${{ secrets.README_API_KEY }}

      # project ai
      - name: Project AI 🚀
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./api/project_ai.yaml --key=${{ secrets.README_API_KEY }}